# Generated by Django 5.0.3 on 2025-09-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='provider',
            name='category',
        ),
        migrations.AddField(
            model_name='provider',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.category'),
        ),
    ]
